version: '3.7'

services:
    # db:
    #     image: postgres:11
    #     environment: 
    #         - POSTGRES_PASSWORD=postgres
    #     ports:
    #         - "5433:5432"
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        # depends_on: 
            # - db
    # redis:
    #     image: "redis:alpine"
    #     ports:
    #         - 6379:6379